import java.awt.Color;
import java.awt.Graphics;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hiram
 */
public class set3Tarea extends javax.swing.JFrame {

    /**
     * Creates new form set3Tarea
     */
    public set3Tarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel1.getHeight();
                int w = jPanel1.getWidth();
                for (int i = 0; i <= w/2; i+=5){
                    g.drawLine(i,h, w/2, h-i);
                    g.drawLine(w-i,h,w/2,h-i);
                    g.drawLine(i,0,w/2,i);
                    g.drawLine(w-i,0,w/2,i);
                    g.drawLine(0,i,i,h/2);
                    g.drawLine(0,h-i,i,h/2);
                    g.drawLine(w,h-i,w-i,h/2);
                    g.drawLine(w,i,w-i,h/2);
                }
            }
        };
        jPanel2 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel1.getHeight();
                int w = jPanel1.getWidth();
                for (int i = 0; i <= w; i+=10){
                    //g.drawLine(i,0, w, i);
                    g.drawLine(0,h-i,i,0);
                    //g.drawLine(0,i,i,w);
                    g.drawLine(w-i,h,h,i);
                    //g.drawLine(0,i, w, i);
                }

            }
        };
        jPanel3 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel3.getHeight();
                int w = jPanel3.getWidth();
                for (int i = 0; i <= w; i+=10){
                    //Parte arribaizquierda
                    g.drawLine(i/2,0 , w/2-i, i);
                    g.drawLine(w/2-i/2,h/2,i/2,h/2-i/2);
                    //Parte arribaderecha
                    g.drawLine(w-i/2,0 , w/2+i, i);
                    g.drawLine(w/2+i/2,h/2,w-i/2,h/2-i/2);
                    //Parte abajoizquierda
                    g.drawLine(i/2,h , w/2-i, h-i);
                    g.drawLine(w/2-i/2,h/2,i/2,h/2+i/2);
                    //Parte abajoderecha
                    g.drawLine(w-i/2,h , w/2+i, h-i);
                    g.drawLine(w/2+i/2,h/2,w-i/2,h/2+i/2);
                }
            }
        };
        jPanel5 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel5.getHeight();
                int w = jPanel5.getWidth();
                for (int i = 0; i <= w; i+=10){
                    //Parte arribaizquierda
                    g.drawLine(0,h/2-i/2,i/2,0);
                    g.drawLine(i/2,h/2-i/2,w/2,i/2);
                    //Parte arribaderecha
                    g.drawLine(w-i/2,0,w,h/2-i/2);
                    g.drawLine(w-i/2,h/2-i/2,w/2,i/2);
                    //Parte abajoizquierda
                    g.drawLine(0,h/2+i/2,i/2,w);
                    //Parte abajoderecha
                    g.drawLine(w,h/2+i/2,w-i/2,h);
                    //estrella
                    g.drawLine(w/4+i/4,3*h/4,w/2,3*h/4-i/4);
                    g.drawLine(3*w/4-i/4,3*h/4,w/2,3*h/4-i/4);
                    g.drawLine(w/4+i/4,3*h/4,w/2,3*h/4+i/4);
                    g.drawLine(3*w/4-i/4,3*h/4,w/2,3*h/4+i/4);
                }
            }
        };
        jPanel6 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel6.getHeight();
                int w = jPanel6.getWidth();
                for (int i = 0; i <= w/2; i+=5){
                    g.drawLine(i,h, w/2, h-i);
                    g.drawLine(w-i,h,w/2,h-i);
                    g.drawLine(i,0,w/2,i);
                    g.drawLine(w-i,0,w/2,i);
                    g.drawLine(i,h-i,w/2-i,h/2-i);
                    g.drawLine(w-i,i,w/2+i,h/2+i);
                }

            }
        };
        jPanel7 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel1.getHeight();
                int w = jPanel1.getWidth();
                for (int i = 0; i <= w/2; i+=5){
                    //Techo
                    g.drawLine(0,h/2-i,i,0);
                    g.drawLine(w,h/2-i,w-i,0);
                    //centro
                    g.drawLine(i,h-i,w/2,h/2-i);
                    g.drawLine(w-i,h-i,w/2,h/2-i);
                    g.drawLine(i,h-i,w/2+i,h/2+i);

                    //g.drawLine(i,h/2, w/2, h/2-i);
                    //g.drawLine(w-i,h/2,w/2,h/2-i);
                    //g.drawLine(i,h/2,w/2,h/2+i);
                    //g.drawLine(w-i,h/2,w/2,h/2+i);
                }

                for(int i = 0; i <= w/4; i+=5){
                    //piso
                    g.drawLine(w/4+i,h,w/2,h-i);
                    g.drawLine(3*w/4-i,h,w/2,h-i);
                }
            }
        };
        jPanel8 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel1.getHeight();
                int w = jPanel1.getWidth();
                for (int i = 0; i <= w/2; i+=5){
                    //Parte arribaizquierda
                    g.drawLine(i,h/2,0,i);
                    g.drawLine(i,i,w/2,h/2-i);
                    //Parte arribaderecha
                    g.drawLine(w/2+i,h/2,w,h/2-i);
                    g.drawLine(w-i,i,w/2,h/2-i);
                    //Parte abajoizquierda
                    g.drawLine(i,h/2,0,h-i);
                    g.drawLine(i,h-i,w/2,h/2+i);
                    //Parte abajoderecha
                    g.drawLine(w-i,h/2,w,h-i);
                    g.drawLine(w-i,h-i,w/2,h/2+i);
                }
            }
        };
        jPanel9 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g) {
                super.paintComponent (g);
                int h = jPanel9.getHeight();
                int w = jPanel9.getWidth();
                for (int i = 0; i <= w; i+=10){
                    //Parte arribaizquierda
                    g.drawLine(0,h/2-i/2,i/2,i/2);
                    g.drawLine(w/2,i/2,w/2-i/2,h/2-i/2);
                    //Parte arribaderecha
                    g.drawLine(w,h/2-i/2,w-i/2,i/2);
                    g.drawLine(w/2,i/2,w/2+i/2,h/2-i/2);
                    //Parte abajoizquierda
                    g.drawLine(0,h/2+i/2,i/2,w);
                    //Parte abajoderecha
                    g.drawLine(w,h/2+i/2,w-i/2,h);
                    //estrella
                    g.drawLine(w/4+i/4,3*h/4,w/2,3*h/4-i/4);
                    g.drawLine(3*w/4-i/4,3*h/4,w/2,3*h/4-i/4);
                    g.drawLine(w/4+i/4,3*h/4,w/2,3*h/4+i/4);
                    g.drawLine(3*w/4-i/4,3*h/4,w/2,3*h/4+i/4);
                }
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jLabel1.setText("Ejemplo 1");

        jLabel2.setText("Ejemplo 4");

        jLabel3.setText("Ejemplo 6");

        jLabel4.setText("Ejemplo 9");

        jLabel5.setText("Ejemplo 2");

        jLabel6.setText("Ejemplo 3");

        jLabel7.setText("Ejemplo 8");

        jLabel8.setText("Ejemplo 5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(set3Tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(set3Tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(set3Tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(set3Tarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new set3Tarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
